### ISSUE TITLE
2.9.3 Install error

### ISSUE THREAD

**Issue by Tinman77** [codeproject/CodeProject.AI-Server#186]
**Area of Concern**
- [ ] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**

**Expected behavior**

**Screenshots**

**Your System (please complete the following information):**
 - CodeProject.AI Server version: {e.g. 2.3.1]
 - OS: [e.g. Ubuntu 20.04]
 - System RAM [e.g. 16Gb]
 - GPU (if available) [e.g. GeForce RTX 3060]
 - GPU RAM (if available)  [e.g. 4Gb]

**Additional context**

Installed 2.9.3 had this error when installing, but it does start and is working fine.

![304](https://github.com/user-attachments/assets/0ea31dd2-863d-4dd8-94a0-2b96b1cebf2b)

![305](https://github.com/user-attachments/assets/5da17385-4901-4520-852f-5a107ae8192f)

**Comment by ChrisMaunder** [comment]
I cut a very large corner and rereleased 2.9.3 this morning with the same version since it was an installer not a server issue. Did you download the installer before 9am US Eastern or after?

if after, please open an explorer window and go to %TEMP% (it's your temp folder) and look for a installer error log file. If you could paste that here that would be great

**Comment by Tinman77** [comment]
I just deleted it all and downloaded just now and did a install. This time it worked perfect :)

**Comment by ChrisMaunder** [comment]
Excellent. I've bumped the installer zip to a x.x.x.1to avoid these issues.
