### ISSUE TITLE
YOLOv8 timeout while downloading. Increasing Timeout value?

### ISSUE THREAD

**Issue by war4peace** [codeproject/CodeProject.AI-Server#224]
**Area of Concern**
- [X] Server
- [X] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [X] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Updating from 2.6.5 to 2.9.5, YOLOv8 keeps erroring out with "Response timeout. Try increasing the timeout value".
Where and how do I increase this dreaded "timeout value"?
No, it's not my Internet connection, I have Gigabit fiber.

**Expected behavior**
YOLOv8 to successfully download.

**Screenshots**
![image](https://github.com/user-attachments/assets/34da766a-033f-44fc-8b21-6ca875a5442e)

**Your System (please complete the following information):**
 - CodeProject.AI Server version: {e.g. 2.9.5]
 - OS: [Windows 11]
 - System RAM [32 GB]
 - GPU (if available) [GeForce RTX 4060]
 - GPU RAM (if available)  [8 GB]

**Additional context**

I never learn. Every update attempt of CPAI is a slog, since, well, forever. I have grown to allocate 4+ hours every time I am trying to update from one version to another. I would gladly pay for this "update never works well" issue to go away.

**Comment by ChrisMaunder** [comment]
The appsettings.json file contains the setting

<img width="583" alt="Screenshot 2024-12-10 at 10 37 23 am" src="https://github.com/user-attachments/assets/0add75ee-b7dd-451b-89af-dc5e77147856">

The issue here is that the message you're seeing is 100% correct and 100% unhelpful. When an install is requested, a call is made to the server which then initialises the call to the cloud to download the module, then it downloads, then it unpacks and starts the install, which involves further downloading and installing. Depending on the module, your bandwidth, the load on the hosting provider, the speed of your machine to install the packages, and the speed of the package hosting (PyPi or Nuget) this can take a while.

Meanwhile, the dashboard has made a call to the server to initiate the install, and is sitting there watching, and after the defaul 20 mins it gives up watching.

**The install is still happening**

What's needed is for the install call to be made, and then return immediately, and then further polling calls (or a signal-R connection) be made to constantly update on the status.

Even with a timeout being reported, the logs should have still (hopefully) shown further progress.

**Comment by war4peace** [comment]
Thank you for your response.
The timeout message appears very quickly (less than 10 seconds), certainly nowhere near 20 minutes.
The module is YOLOv8.
My bandwidth is 1000 Mbit download.
Load on hosting provider is definitely out of my control.
Machine is fast enough, Intel i3 14100 (yes, on the low side, but should not pose a problem), 32 GB RAM and storage is a 1 TB Samsung EVO 970 nVME SSD.

As for whether the install is still happening, I can confirm that it took the better part of 1 hour, but it eventually finished installing.
Maybe this type of behavior should be better explained in a log entry or  under the information button.

**Comment by ChrisMaunder** [comment]
So the issue is the message (which I'll fix) and the time. I'm on a 500mps connection and YOLOv8 installs in just a few minutes. Your machine is certainly capable enough. Do you have an anti-virus installed that's slowing things down?

**Comment by war4peace** [comment]
There is no slow-down that I could detect, I am able to monitor throughput on that machine via my Ubiquiti Network Controller, and the download for YOLOv8 was very slow.
YOLOv5 did not exhibit the same behavior, it installed quickly. 

At any rate, now YOLOv8 is indeed installed, I will switch from v5 to v8 tomorrow and test some more.

**Comment by thecamaroguy** [comment]
I set my value in the HOURs instead of minutes...Every time I download a new Docker version, I start it, edit that file, restart it...then start installing/upgrading Modules.
My internet is via StarLink so the speeds are all over the place.
