### ISSUE TITLE
Trying to update Docker pre-installed modules: "A 'pre-installed' module can't be downloaded"

### ISSUE THREAD

**Issue by melyux** [codeproject/CodeProject.AI-Server#59]
**Area of Concern**
- [x] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [x] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Pre-installed modules on the base Docker image (Face Processing, Object Detection (YOLOv5 .NET), Object Detection (YOLOv5 6.2)) can't be updated. (They also can't be removed, but that's a different issue.)

**Expected behavior**
I should be able to update the pre-installed modules.

**Screenshots**
<img width="781" alt="image" src="https://github.com/codeproject/CodeProject.AI-Server/assets/10296053/4f41f063-4099-49b7-a69d-b46141c567a2">

**Your System (please complete the following information):**
 - CodeProject.AI Server version: latest
 - OS: Docker
 - System RAM: 16GB
 - GPU: Intel internal

**Comment by AKHwyJunkie** [comment]
FWIW, I'm seeing this exact same thing.  Also running Docker instance.  I'm running the latest available version, 2.1.11 Beta.  I see the same error on both the modules I might be able to update, FaceProcessing and Yolov5.6.2.  Full error logs from system are as follows:

```
11:49:39:Preparing to install module 'ObjectDetectionYolo'
11:49:39:Module description for 'ObjectDetectionYolo' is invalid. A 'pre-installed' module can't be downloaded
11:57:57:Preparing to install module 'FaceProcessing'
11:57:57:Module description for 'FaceProcessing' is invalid. A 'pre-installed' module can't be downloaded
```
In the FWIW department, I can also demonstrate this in 2.1.9 as well.  It occurrs on both active and inactive modules, same exact error.  I have tried stopping the modules and still get the same error.  I also didn't see the modules update in my test migration from 2.1.9 to 2.1.11, but I'm not sure if that would be expected behavior.  I'll keep poking at it and will update if I find a workaround.

**Comment by matthewDDennis** [comment]
Could you try and install a different module.
If this fails the same way, it may be that the CodeProject.AI Server is not able to connect to the internet to download the modules.
How did you start the Docker Container?

**Comment by melyux** [comment]
> Could you try and install a different module.
> 
> If this fails the same way, it may be that the CodeProject.AI Server is not able to connect to the internet to download the modules.
> 
> How did you start the Docker Container?

Other modules download and install correctly

**Comment by sanderdewit** [comment]
same issue here on multiple devices running Docker.

**Comment by AKHwyJunkie** [comment]
> Could you try and install a different module.

I also tested installing a new module on my instances, works fine in both v2.1.9 and v2.1.11

**Comment by sanderdewit** [comment]
I can confirm, installing other modules work fine.

**Comment by xm4rcell0x** [comment]
i have the same issue!

**Comment by sanderdewit** [comment]
when removing the modules from preinstalled folder and installing them via the gui, it works fine.

**Comment by ChrisMaunder** [comment]
This has been fixed in the latest version
