### ISSUE TITLE
Coral support for face & license plate

### ISSUE THREAD

**Issue by laurentopia** [codeproject/CodeProject.AI-Server#72]
Just because the Coral dual TPU came back in stock on Mouser and I bought 2 :>

**Comment by ChrisMaunder** [comment]
I'm jealous! We are focussing more on providing support for AI and AI setup/installs rather than digging deep into individual modules. If there's an OCR and license plate detection TF-Lite, edge TPU compiled model available then adding that is trivial, but we generally won't be training individual models ourselves. Sorry!
