### ISSUE TITLE
Add my own Python module

### ISSUE THREAD

**Issue by Cilouche** [codeproject/CodeProject.AI-Server#83]
Hello,

I'd like to add my custom classification module to CodeProject.AI (python module). 
I followed the instructions described on this page `https://www.codeproject.com/ai/docs/devguide/module_examples/add_python_module.html`

but when I launch the server by starting a new debugging session in Vs Code, my new module did not appear on the CodeProject.ai dashboard? 
any suggestion please?

Thanks

Server
 Runtime Python39, .NET
 Module packages Tensoflow2.6.2

Your System 
 - CodeProject.AI Server version: {e.g. 2.3.1]
 - OS: Window 11
 - System RAM 32GO

**Comment by ChrisMaunder** [comment]
I can't help without more details, but please review https://www.codeproject.com/Articles/5377531/CodeProject-AI-Module-creation-A-full-walkthrough

**Comment by wyyyyyy123** [comment]
I think the issue seems to be related to the deployment process of a custom Python module on the CodeProject.AI-Server. Possible causes include network problems, server issues, or non-compliance with module requirements. By systematically checking these potential problems and following the solutions outlined above, you should be able to identify and resolve the issue. If all else fails, contacting support is the best way to get personalized assistance and a definitive solution.
